[options]
db_host = False
db_port = False
db_user = odoo
db_password = odoo
addons_path = addons,projects/myaddons
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$.x8D4HzvXYvxHkOo9d57Tw$lVjzLaJprBX3yX7iEB0X4KfC255dj9SX79x/LPdFn9Sue3rAl2lxmb3j4KZFodyNpzYkmf4vsRn9XZ6RrT6TOw

